version: '3.7'
services:
  app:
    image: pmbanks/ridiculous-thoughts.com:latest
    build: .
    restart: always
    init: true
    env_file: 
      - app.env
      - database.env
    volumes:
      - type: volume
        source: website-nginx-config
        target: /app/config/nginx
      - type: volume
        source: website-static
        target: /static_cdn
      - type: volume
        source: website-media
        target: /media_cdn
    depends_on:
      - database
  server:
    image: nginx:1.15-alpine
    restart: always
    init: true
    volumes:
      - type: volume
        source: website-nginx-config
        target: /etc/nginx/conf.d
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: website-static
        target: /mnt/static
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: website-media
        target: /mnt/media
        read_only: true
        volume:
          nocopy: true
    ports:
      - "80:80"
    depends_on:
      - app
  database:
    image: postgres:10-alpine
    restart: always
    init: true
    env_file: 
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
  watchtower:
    image: v2tec/watchtower:latest
    restart: always
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
volumes:
  db-data:
  website-nginx-config:
  website-static:
  website-media:
